version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run ci:lint

  build:
    docker:
      - image: circleci/node:8.11.0
      - image: bitbankinc/mock-bitbankcc
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: NODE_ENV=testing npm run test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: npm login with token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          context: org-global
      - deploy:
          context: org-global
          filters:
            branches:
              only: production
          requires:
            - build
            - lint
